# Generated by Django 4.0.1 on 2022-01-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
